name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build APK with Docker
        uses: docker://kivy/buildozer:latest
        with:
          args: |
            buildozer init
            sed -i 's/title = .*/title = Drought Stress RF/' buildozer.spec
            sed -i 's/package.name = .*/package.name = droughtstressrf/' buildozer.spec
            buildozer android debug
            
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Drought-Stress-RF-APK
          path: bin/*.apk
